### PR TITLE
Rule 301: skipping turns

### PR DESCRIPTION
**Pull request by VeNomic-Administration**
I suggest to allow it for convenience.
What is the idea behind prohibiting it?

(Pull request by Administration)

### CODE REVIEW

**Comment by AnonymousVeNomicPlayer** [comment]
Does that mean that we pause the game for one turn or is your intention that the next player continues  immediately? In the latter case it might be good to have a time limit for skipping a turn such that the next player still has enough time to propose a rule.

**Comment by Snark1994** [comment]
My preference would be that a player can choose to skip their entire turn by not proposing a rule on their proposal day, in which case the next player is able to propose a rule on the next proposal day as expected.

**Comment by Snark1994** [comment]
(Whichever way you decide, it should be made more explicit in the phrasing of the rule!)

**Comment by Snark1994** [comment]
Sorry, "the close and comment" button is right next to the "comment" button...

**Pull request merged**
