### PR TITLE
Initial rules proposal for a new game

### PR DESCRIPTION
**Pull request by Snark1994**
Here is the writeup of suggestions for the initial rules of a new round. Let me know if you have any objections by Sunday, and if not we can start a new round with Nils' proposal on Monday.

### CODE REVIEW

**Comment by malte-l** [comment]
I haven't heard the term "strict majority" before - do you mean "absolute majority"? I.e. the majority of all players rather than only those voting?

**Comment by Snark1994** [comment]
I meant ">50%" rather than ">=50%"

**Comment by malte-l** [comment]
Ah, ok. I would still prefer to change it to "absolute majority". If we have 10 players, I think rules should not pass if 3 vote yes, 2 no and 5 did not vote on time. 6 approvals should always be required with 10 players. For example we currently have no "holiday" mode and so on if I remember correctly, it can easily happen that it is even known beforehand that certain people will have less possibility of voting.

**Comment by Snark1994** [comment]
I'll change the wording, but my interpretation of the rules as they stand fits with what you want. (Rules pass iff they are approved by a strict majority of eligible voters; a voter approves a rule iff they vote and their vote is "yes")

**Comment by AnonymousVeNomicPlayer** [comment]
I do also have a few remarks:
- my name is still not spelled correctly in the scores.md file (I think we only changed it in players.md and I did not notice that for the whole last game).
- I am a bit confused by 112 and 212. Rule 212 says that it takes precedence over any other rule determining the winner, so in particular over 112 (?). And 112 has the part that when two players satisfy winning conditions and the game cannot continue (which I think can only happen when game cannot continue according to 212) nobody wins, which seems obsolete to me since 212 takes precedence (?). Did you maybe want to append to sentence with takes precedence over any other rule to 112 instead of 212?

**Comment by AnonymousVeNomicPlayer** [comment]
- In 120 in the sentence "Only the first email [...] that [...] satisfies the above conditions shall treated as the email containing the vote." it should be "be treated".
- The phrasing of the judiciary rule does not make it clear to me what exactly happens in the case that there are no more judges left (e.g. two people are involved in a conflict and two judges are ashamed). The phrasing of the rule is "Judgement is repeated with a new player (the previous player in turn order) in place of the Ashamed Judge, if possible". How is the if possible to be interpreted and to which parts of the sentence does it refer? I.e. the judgment should be repeated in any case, right?
- Judgment is also spelled Judgement.

**Comment by Snark1994** [comment]
* Oop sorry, will change your names in the scores file too (we'll get it right someday)
 * You're right with 112 vs 212 - I'll add an exception in 212.
 * My intention with the judging rule was that it should be the previous three people, unless one of them was involved in the conflict, or if one of them became Ashamed. The extra wording was to prevent someone claiming a win because we'd run out of Judges. I'll try to rephrase it: my intention would be that Ashamed judges keep cycling, and if there are too many people who are involved then we just ignore that part of the rule.
 * You mean "Judgement" is sometimes spelt "Judgment"? ;)

**Comment by Snark1994** [comment]
I've made a second attempt; still not sure that the Judgement rule is very well-phrased. If someone else wants to make an attempt at cleaning it up they would be very welcome. (The main points I want to cover are: it should be clear what happens if judges don't vote on time, and there should probably be something along the lines of "people who are involved in the disagreement can't be on the Judiciary, if possible".)

**Comment by AnonymousVeNomicPlayer** [comment]
- Thanks.
- Ok.
- I like the new form much better than the old one. I do not know what exactly your intention is, but maybe you should rather say explicitly that you want a vote by majority than to reference the normal rules on voting. Just in case the normal rules change (e.g. by introducing a rule to buy votes with points), one probably does not want to apply these changes to the judges? At least I would think that judges should decide according to the rules and thus there is no need to buy more votes to overrule other judges. Also it would mean that the judges send their votes by email to the current player. In case judgement was invoked after a turn and the next player did not start his turn yet, it is not clear who this should be.
- Since you are British, yes. And maybe I should rather practice how English verbs are *spelt* in the past than Danish ones :)

**Comment by AnonymousVeNomicPlayer** [comment]
And let me ask one more thing since I forgot already what we discussed on Wednesday: Did we say that we do not yet want to implement the possibility to change immutable rules directly by a unanimous vote? I can't remember what the final decision on that point was, but would like to remark that it would take at least 3 turns to implement it (probably more since the actions of what a rule change is and the way it is voted on are defined in different rules). Also, I am not convinced that it is a good idea to make the rule on possible rule changes mutable...

**Comment by malte-l** [comment]
I agree that without "absolute" the rules should already be interpreted in that way, but I think it is good to make that explicit to make sure that it must be interpreted that way. I also think that >50% should be required rather than >=50%, but I think "absolute majority" also includes that.

Regarding the spelling of judgment: It is also spelled "judgment" in British English, when in legal contexts (see for example https://en.oxforddictionaries.com/definition/judgement). It is also the older from, and got mostly replaced in non-legal contexts by "judgement" between 1650 and 1700. So I think also in British English, in this context it should be "judgment" if we want to be really precise about spelling, because we are kind of pretending/simulating that this is a legal thing (rather than personal opinions/expectations etc.). More information can also be found at http://grammarist.com/spelling/judgment-judgement/.

**Comment by Snark1994** [comment]
I've reverted the spelling of Judg(e)ment, I did not know that.

We had decided that we would not include the option to modify or repeal immutable rules with a unanimous vote; but I found your argument convincing just now, so I have added that change (given I was the main one who disagreed at the meeting). If anyone has strong feelings to the contrary then let me know and we can change it back, but spending 3 rounds to modify a rule doesn't seem super fun.

**Pull request merged**
