### PR TITLE
Rule-303

### PR DESCRIPTION
**Pull request by peteroestergaard**
I propose that a player has to have at least one item in order to take their turn

### CODE REVIEW

**Comment by Snark1994** [comment]
This seems a little broken... As written, unless you give the hat to the next player in line, they will win the game because they can neither skip nor take their turn, not being in possession of an item.

If your intention was "play passes to the next player with an item", then it needs rephrasing. And I'm not completely sure I'd be happy with that, at least until we have more items in play (e.g. it seems that 3 people could conspire to ensure that nobody else ever gets a turn to propose a rule)

**Comment by malte-l** [comment]
I would suggest suspending/slowing down moving on with the new proposals until the current status of the game is clarified, the results of the previous vote have not yet been announced and the hat currently belongs to N. even though the repository says otherwise.

**Comment by peteroestergaard** [comment]
The intention is as written! The hope is that it creates an incentive to create more objects, as well as perhaps providing interesting possibilities later in the game

**Comment by Snark1994** [comment]
Fair enough! What about the fact that it seems the next player will win (being unable to legally complete their turn) unless you give them the Hat?

**Comment by AnonymousVeNomicPlayer** [comment]
I have the same problem as Josh, with the current formulation as soon as someone forgets to pass the hat to the next player, the next player wins.
Even if the rule just said whoever does not have an item may not propose a rule it would imply that the one currently owning the hat, is the only one allowed to propose rules until he decides to give the hat away.
If this is supposed to be some smart winning move, I cannot see how it gives you any advantage. If you do not plan to trick us on the voting day, I would guess that chances that the rule passes are pretty low.

**Comment by peteroestergaard** [comment]
Yes the intention is that the nominations for the hat are forced until a new item is created :) I was hoping that the result would be that new items are created quite quickly, and then everyone has to be a little bit careful in case they accidentally cause somebody else to win... But I get the feeling that it's not such a popular way to achieve what I had in mind so how about something like 'the game may be won only when every player is in possession of at least one item' ? Thus the same motivation that I want lots of new items to be created...

**Comment by Snark1994** [comment]
Ah I see, that makes more sense; I'm happier with your "the game may be won only when..." formulation, but I think I would be happiest with a proposal for a fun item! (Be the change you want to see in the world ;) ).

**Comment by AnonymousVeNomicPlayer** [comment]
I think that the "the game may only be won formulation" also isn't exactly what you want, because it does not encourage people to create more items if there is only a minority that does not possess an item yet. Neither does it encourage people to give away their items (like the top hat of good karma).

**Comment by cleborys** [comment]
Or reformulate such that it does what you originally intended but without the win condition thing?

**Comment by cleborys** [comment]
But actually I feel the original intention is a bit too dangerous...
So maybe a fun item instead, as Josh said?

**Comment by nilsbeyer** [comment]
I think we will soon be at a point where Clemens initial suggestion of a python program makes sense.
(To track item interaction and point generation)

**Comment by nilsbeyer** [comment]
Is it allowed to still discuss the rule on voiting day?
Or give my opinion on it?

**Comment by Snark1994** [comment]
I can't think of anything preventing it, so yes you probably are

**Comment by malte-l** [comment]
Regarding N.'s comment on C.'s initial suggestion: I agree that the format of just proposing rule changes which change the rules file is a bit limiting and hinders some extensions such as items. For example it seems we now have to add a new rule in rules.md for every item to be introduced or changed, and the text is then replicated in items.md. This clutters rules.md, and we are already close to the limit set by rule 209.
I plan to introduce a rule-change next turn that would be the first step towards splitting up the things we pass and their implementation as rules. I.e. we would then pass "bills", which might be collected in numerical order in some file, together with whether they passed or not, and they specify a change in a rule, or an item, etc.

**Comment by malte-l** [comment]
What was the result of the vote? Updating the scores etc. before stating truthfully in a comment here how everyone voted violates the last point of rule 120... Also, how did Clemens obtain the hat? The procedure prescribed by the hat's description seems to not have been followed...

**Comment by peteroestergaard** [comment]
Sorry Malte, I forgot you weren't on the WhatsApp group. I received one vote for and one vote against, apart from my own vote. So the proposed rule didn't pass. I was the previous owner of the hat and I nominated Clemens as the new owner of the hat.

**Comment by malte-l** [comment]
So who voted for apart from you? [And there is no one not voting (see this discussion on the previous turns), everyone that did not send anything voted no.]

**Comment by peteroestergaard** [comment]
Erik Eriksen voted yes, Harald Bohr voted no, and yes whatever sure

**Comment by malte-l** [comment]
I can find none of these people on the players list, and there are people on the players list that you did not mention. If this is supposed to be some kind of joke, I don't find it funny as it completely unnecessarily holds up the game. Please follow the rules (120 specifically) and state accurately and truthfully whether each individual eligible voter has approved the change or not.

**Comment by peteroestergaard** [comment]
No joke, Malte, that's who the emails appear to be from. I believe that Harald Bohr is Nils and Erik Eriksen is Clemens. And surely by your own logic you can work out what to do with the missing information?

**Comment by Snark1994** [comment]
I think Peter was pretty clear... In any case, what Peter said was correct; Clemens and Peter voted yes, myself, you, Philipp and Nils voted no.

**Pull request closed without merging**
