### PR TITLE
Rule 304: Change rule 302 (voting procedure)

### PR DESCRIPTION
**Pull request by malte-l**
Hi,

so I started from Peter's proposal and made it a bit more detailed to hopefully address most of the criticism.
Here is what this rule does:
* The first sentences just setup the rule, saying that when voting on a rule this procedure must be followed and that terms like "voting day" refer to the voting day that is associated to the vote we are talking about and not some other voting day (this makes the formulations below that shorter and more readable)
* To make sure the proposer is reachable, they must now specify an email address in the comments to the pull request, before the vote. Voting is then done by email, so carrier pidgeons may not be used (using possibly multiple communication channels for voting, particular if the proposer doesn't know the full list, would have the problem that the proposer never knows whether they checked all channels and received all messages. Also, some might make it difficult to determine which one was sent last etc. Having exactly one email address specified that is used should not have those problems)
* The emails sent as votes must have a specific subject line that refers to the rule change, and if it should be counted as an approval the first line should be "APPROVE". 
* If votes sent after the voting day is over count there might be an incentive for the proposer to either wait as long as possible after (eg. missing yes votes) or to stay awake and immediately announce the result a minute after midnight (eg. if players don't voting are not counted either way, to prevent them from voting no). I don't want that, so late votes are not counted.
* If people vote multiple times, the last one (that is before the end of the voting day) counts.
* Up to now, rules were passed even though not everyone had voted on time, and not voting was implicitly taken to be an approval. As it is probably hard to enforce everyone from voting on time every turn, not sending an email will thus be counted as an approval. I was also thinking as an alternative to just reduce the number of people required for unanimity etc. but that might conflict with rule 203 etc.
* Votes should be secret until they are counted
* The votes are then revealed on the pull request. I chose 15 hours after the end of the voting day a little arbitrarily, but the idea is that the proposer should usually not have to significantly change their day rhythm to do this as quickly as possible, so I would like to give time until at least the early afternoon of the next day, but on the other hand the next proposer would want to know if the change was approved or not before proposing their own rule, so it can't be until the end of the next day. Going forward we might want to change the proposing days to have a day in between the voting day and the proposal day?

Comments are very welcome!

PS: Now I also noticed what that stuff with markdown numbering was about, I will change the numbering with "ii" etc. in a later commit

### CODE REVIEW

**Comment by cleborys** [comment]
I would prefer the first vote to count, instead of the last one, if there are multiple votes.
I don't think being able to change your vote brings that many benefits and I would like to avoid the possibility of unnecessary mindgames (even if only the proponent should know the votes and has no choice himself).
Also, the case of simultaneous votes should be handled (it seems pretty easy to send two contradicting emails simultaneously).

**Comment by Snark1994** [comment]
I'm unhappy with my email address being publicly visible / scrapeable. I'd favour a system where we agree among ourselves a "designated email address" for each person that is expected to change only infrequently.

I think the email subject should be less specific: I don't want my "REJECT" treated as an "APPROVE" because I misspelt one of the words in the subject, for example.

Once unanimity is not required, I think "no vote is APPROVE" is too lax - if 2 people forget to vote on time, then we only need 1 person other than the proposer to carry the motion. (Which event has already happened.) I think defaulting to "REJECT" is safer in terms of game stability, though more frustrating. So perhaps a future rule could introduce compensation (e.g. in the form of points) for people who vote for a motion that doesn't pass, which could have passed if everyone who didn't vote had voted to approve.

Reword: "stating accurately and truthfully for each elegible voter whether they have approved the change or not" -> "stating accurately and truthfully whether each individual elegible voter has approved the change or not"

**Comment by cleborys** [comment]
(I didn't actually read the changes, only your tldr (am on the phone), so ignore me if there is something in the rules to handle that already)

**Comment by cleborys** [comment]
Maybe a good catch-all is adding, that if the vote of a player is ever equally approve as disapprove, it will default to whatever we pick for players who don't vote at all.

**Comment by AnonymousVeNomicPlayer** [comment]
I agree with Josh that it might be good to have a list of designated email addresses, both of the proposer and all eligible voters. At the moment I see the problem that someone could create a lot of fake email accounts that resemble the names of the current players and then send emails acting as the other players. In this case it is not clear who actually sent the emails.
An elegant way to set up such a list would be that (in case this rule passes) everyone sends an email to Malte and he responds with a list of the email addresses as soon as he received all of them. If Malte has an email account he uses for spam mail and for which he does not mind if it appears in a git hub comment, he could use this one. Otherwise I can offer my spam account.

**Comment by Snark1994** [comment]
Or just "to the address that will be advertised in the WhatsApp chat", assuming Malte is willing for the email he has previously been using for nomic to be advertised that way (I believe that myself, Clemens and Philipp are all aware of the address, so can check that it has been accurately broadcast).

**Comment by malte-l** [comment]
I changed a couple of things (will change at least one more thing, how to distribute email addresses, a little later):

* changed the formatting a little
* made the first vote count, not the last one. Also added something so that if it can't be decided which mail was last, then this is treated as nothing sent.
* changed the revealing-the-votes wording as suggested by Josh.
* If unanimity is not required for the proposal to pass, then not voting only counts as half an approval-vote. This hopefully alleviates Josh's concerns: Now if majority is needed, then not voting in practice just reduces the number of players having voted and being relevant for what "majority" means. I think this should work like this, actually reducing the number of players is probably more difficult because of the rule that everyone needs to vote. Another way to view this would be that not voting is like an abstention, but the rules don't talk about abstentions so I didn't want to introduce them in this rule.
* The subject line now doesn't need to be precisely what I suggested before, it just needs to clearly contain the information that it is a vote and for which rule change.

This should hopefully solve every issue people mentioned other than the thing with distributing the initial emails and making sure that there is only one email every player can send from. Is that correct? I will deal with these two problems later (already have an idea how to do it, but wanted to write these things first).

**Comment by malte-l** [comment]
I now also changed the method of finding out about the email addresses. Everything is collected first at one address and then distributed from there. I also would like take up AnonymousVeNomicPlayer's offer of using their spam email account if that is ok (could you send me the address?). I hope that this procedure is ok for everyone. It is just to get started with using emails so will only be applied once.

**Comment by Snark1994** [comment]
It seems okay to me; minor grammar point, it should be "the player's vote" instead of "the players vote" at one point.

**Comment by AnonymousVeNomicPlayer** [comment]
You could use meinspamemailkonto@gmail.com as email address if people do not mind that I will distribute the mail addresses.

**Comment by malte-l** [comment]
I fixed a couple of spelling mistakes, including the one pointed out by Josh. I also replaced the placeholder for the email address used for initially distributing the email addresses by the one given by Philipp. With this I think the proposal should now be in a form that addresses all the concerns voiced before.

**Comment by malte-l** [comment]
VOTE: APPROVE

**Comment by Snark1994** [comment]
Vote: APPROVE

**Comment by AnonymousVeNomicPlayer** [comment]
VOTE: approve

**Comment by peteroestergaard** [comment]
VOTE: approve

**Comment by nilsbeyer** [comment]
VOTE: approve

**Comment by Smaug123** [comment]
I'm afraid I'm going to concede the game under 113. I'd hoped that there would be time and mental energy to put into another game, but I'm pretty sure there won't be :( 

Under 201, that means malte-l must remove me from the players list in `players.md`.

**Comment by malte-l** [comment]
I have removed smaug123 from the players list according to rule 113 and 201.

Clemems hasn't voted in the voting day and all other active players at the emd of the voting day voted to approve, so similarily to how such situations were handled before I will interpret this as the rulechange having passed. I will wait until noon to merge the change to give people time to imvole judgement if they want to do that (this rule change fixes the late-voting issue so this should be the last time ot arises :) ).

**Comment by cleborys** [comment]
Er, yup. I would have voted to approve, just let midnight pass, apparently :/

**Comment by malte-l** [comment]
ok, great. i will merge and update points immideatly!

**Comment by malte-l** [comment]
ok, as there was no objection / judgement invoked, I will now finish the turn.

**Comment by malte-l** [comment]
ok, I updated the scores, including removing smaug123, after merging the pull request. So now it is Philipp's turn.

**Pull request merged**
