### PR TITLE
Rule 309: By the twitching of my thumbs...

### PR DESCRIPTION
**Pull request by Snark1994**
Players can now move the minotaur _N_ spaces in a turn by paying _N^2_ points. 
I have also indicated which rules are epochal (the ones explicitly mentioned in my previous rule, plus I am proposing that the current rule be epochal), and added a (non-legally-binding) useful reference for all the things I think need to happen during a turn...

### CODE REVIEW

**Comment by AnonymousVeNomicPlayer** [comment]
What exactly do you mean by "The minotaur is teleportable by the black hole"? That it reappears at (1,1) without anything else happening?

**Comment by AnonymousVeNomicPlayer** [comment]
And I've seen that there are some broken references to the former rule 305, now 308. What's the procedure to fix that?

**Comment by Snark1994** [comment]
Would be nice to have more than 30 minutes to change stuff in my rule before Sunday, just saying :P

I believe Malte "must" have updated all references to rule 305 when he modified the rule; so by updating the references now, I'm just making the github reflect the true state of the game again.

As you say, the minotaur should be teleported to (0,0) in the same way that a king is if the king ends up on the black hole. I've clarified this (I didn't want to say "minotaur interacts with BH in the same way as a king" because it doesn't make sense for the minotaur to lose points)

**Comment by AnonymousVeNomicPlayer** [comment]
You're completely right about the late response, sorry for that. I just forgot to check the rules during the day. (I might blame it on the pizza roles though.)

**Comment by AnonymousVeNomicPlayer** [comment]
I give the hat to M.

**Comment by Snark1994** [comment]
Nobody gets bounty points, nor does anybody move. Malte gets 4 points and ownership of the hat. Josh scores 18 points for a successful proposal.

**Pull request merged**
