### PR TITLE
Rule 307: themes

### PR DESCRIPTION
**Pull request by Snark1994**
I introduce themes to the game: a game is henceforth referred to as an "epoch", and has a theme chosen by the winner of the previous epoch (in this case, Philipp, though that was slightly coincidental). At the end of every epoch, all epochal rules are repealed.

### CODE REVIEW

**Comment by Snark1994** [comment]
Everyone except Malte voted yes. I'll update scores and board after Clemens does!

**Comment by cleborys** [comment]
Yup, sorry.
I was missing the decision whom the top hat of good karma passes to, sorry, should have said so.

**Comment by Snark1994** [comment]
Åh, that decision comes after the declaration of who voted for what (and I wasn't going to pass it on this round in any case, if I recall correctly the owner "may" nominate a new owner)

**Comment by cleborys** [comment]
Ok sorry, my bad.
One moment, then :)

**Comment by Snark1994** [comment]
I am not passing the hat on this round.

**Comment by Snark1994** [comment]
Philipp and I both move up one. I'm removing Nils and Philipp's kings from the board.

**Comment by Snark1994** [comment]
I gain 12 points for my rule, Malte gains 10 points for voting "no", Clemens and Philipp each lose 10 points for being isolated. I've also removed Nils and Peter from the scores file (and when I said I removed Philipp's king previously, I of course meant Peter).

**Comment by AnonymousVeNomicPlayer** [comment]
I think that the value of BOUNTY should be adjusted, so Clemens and me only loose 5 points

**Comment by Snark1994** [comment]
By my reading of the rules, that only happens if all players are isolated; if it's a proper subset then I think bounty stays as it is.

**Comment by AnonymousVeNomicPlayer** [comment]
Sorry, your completely right. I was too lazy to read the rules again and it was only in a former version of the rule that Bounty is always adjusted.

**Pull request merged**
