### PR TITLE
Update Board

### PR DESCRIPTION
**Pull request by AnonymousVeNomicPlayer**
Actually it seems that I did not read my own rule careful enough, because I thought that moving kings would be allowed for the first time when Niels B. is a proposer. But I received a move command by email and cannot find a reason why moving now should be forbidden.
The rule says in the first bullet that at the moment when it comes into existance, everyone shall get a king on the (0,0) square and in a later bullet that after voting, but before determining scores, kings shall be moved.
I wanted to give people the chance to convince me of the opposite, so I did not commit these changes to the master branch yet.

### CODE REVIEW

**Comment by Snark1994** [comment]
I'll check properly later, but I don't think the rule has passed until you announce the result, and certainly not until all votes are in; so if they emailed their move prior to all votes being in, then that is not valid. (Rules don't apply retrospectively)

**Comment by malte-l** [comment]
I agree with Philipp, and this was also the reasoning that led me to send the move command (it was me):

* By rule 205, the rule-change came into effect the moment voting had ended (not only at announcement), so at midnight. Philipp was still proposer at that time, and continued to be so until after finishing updating the scores (rule 202)
* Directly after that, by rule 305 that had just taken effect, P. had to move the kings before updating the score.
* I can see nothing in rule 305 that makes a turn command that was sent at a time before the rule was in force invalid.
* At the time P. is supposed to evaluate the received turn commands, the rule had taken effect, my email satisfies all necessary properties specified to make it valid (was sent during the voting day, clearly stated that it refers to the board, only email sen about that, the email contained precisely one of the four directions and the square on which the king is supposed to move exists)
* At the time I sent the email, the rule saying that I may send such an email did not yet exist. However, there did not exist any rule disallowing the sending of such emails, so by rule 117 it is allowed [I could for example also have sent an email to P. stating that I bet a certain number of points on the outcome of the vote, that would have been totally allowed, just without effect (yet), as there is no rule implementing betting.]

I think it is clear that P. received a direction from me. The rule explicitly states what the test is for the move to be a valid move (and if it is, it has to be carried out), and that has only to do with things happening on the board, such as moving to an existing square.

**Comment by Snark1994** [comment]
The rules say `305) Players may move their king by sending a direction (up, down, left or right) to the proposer of a rule during the voting day in a separate email from their vote, that clearly states that this email relates to the board. [...] Before updating the points the proposer of a rule shall move the kings of each player by one square in the direction received if this move is valid [...] The state of the board can only change if this is explicitly allowed by a rule.`

There is also `107) No rule-change may take effect earlier than the moment of the completion of the vote that adopted it, even if its wording explicitly states otherwise. No rule-change may have retroactive application.`

So I think that your move is only valid if the rule had passed before you sent the email. The state of the board can only change if this is explicitly allowed by a rule; the only rule explicitly allowing changing the board is rule 305; and at the time you sent the email this rule did not exist. You were of course allowed to send the email, but it had no board-affecting-effect.

If you still disagree, I think I'd be happy to invoke judgement (it's probably not an important point, but we haven't had judgement invoked yet!).

**Comment by malte-l** [comment]
I think J.'s argument is based on the assumption that the board is supposed to change when the email is sent, and thus the rules non-existence at that time is a problem. I argue that the board only changes after the voting when the emails are "evaluated", and it is thus irrelevant whether the rule was in effect when the email was sent, only that it is in effect when the emails are "evaluated".

But nowhere in the rule does it claim that the board positions change when the email is sent, as the email only contains "a direction". This is something that is only evaluated after the voting day, and then rule 305 specifies that the new positions are to be evaluated from the emails and then "proposer of a rule shall move the kings of each player", ie. I think it is quite explicit that the movement / change of position happens at *that* time, when the proposer goes through the emails and evaluates them after the voting has ended.

**Comment by Snark1994** [comment]
It is not based on that at all. The question is "Why should I interpret this email I got from Malte as being related to nomic?". The answer being, "there is a rule that says that I should". However, this rule only came into existence after the email was sent, so when you sent the email there should have been no expectation that Philipp would interpret the email as including an instruction to move your king.

**Comment by malte-l** [comment]
Let me add that this argues that it is explicit that the board position changes after voting has ended. But furthermore there can be found nothing contrary in the rule (nothing saying that the position changes before that. The closest thing is that "Players may move their king by sending a direction", which one hypothetically could interpret as meaning implicitly that the kings already move then, but combined with "the proposer of a rule shall move the kings of each player by one square" later this would imply there are two moves in the same direction happening in each turn! Also, the last points says that the board state only may change if the rules *explicitly* says so, so the first one of those which is not explicit can not be it, so the state changes in the second occasion, at evaluation of the emails.

**Comment by malte-l** [comment]
Yes, the question is "Why should I interpret this email I got from Malte as being related to nomic?", but this question is asked at at a time when the rule is in effect, and the email has all the properties it prescribes for it being valid. I completely agree that when I sent the email the email had no effect on the game and had empty meaning *at that point in time*, but it got meaning in the evaluation stage later, because the rule existed then.

**Comment by Snark1994** [comment]
...but nowhere in the rules does it describe separate "sending" and "evaluation" stages. It is a matter of interpretation when this validity check should occur.

**Comment by malte-l** [comment]
Sure it does. This is what I tried to work out in the comment that starts with "Let me add that [...]".

Or what do you mean with "separate stages". Of course this is not something that needs to be called explicitly like that, but the rule clearly separates sending the emails and the moment where the change of state of the board happens. The proposer of the rule "move[s] the kings of each player" at a point in time after the voting ended, so the state of the board changes there. If you also interpret the state of the board as changing when "Players may move their king by sending a direction", then the king moves two steps each turn!  A consistent interpretation where there is only one step moved each turn is that the first sentence is to be interpreted as meaning that "Players may [cause their kings to] move [at a later stage] by sending a direction".

**Comment by Snark1994** [comment]
Absolutely! And my point is that you were not permitted to cause your king to move at a later stage by sending a direction, because that was not an option at the time you sent your email.

**Comment by malte-l** [comment]
Well, but I certainly do not claim that I caused my king to move by sending the direction at the time that happened. I am only claiming that my king is moved by Philipp right before updating the points because there happens to be a certain email in his inbox, satisfying the requirements (the command is "up" or "right", not "left" or "down" or something that is not a direction, the subject line refers to the board etc.).

**Comment by Snark1994** [comment]
I think in that case, I shall invoke judgement.

**Comment by Snark1994** [comment]
I feel you and I should recuse ourselves, so the jury is Nils, Clemens and Peter? Nils' turn has started, so it carries on, by my reading of rule 211.

**Comment by malte-l** [comment]
I think in case Philipp is still of their original opinion (at the start of the pull request), a good procedure would be to merge the pull request, then with that there is an action you can definitely invoke jugment against. The move should have happened before the score is updated (which already happened), at least after the merge there is no doubt that it is Nils' turn.
I think because of that the players for the jury count back from Nils (and not including them), is that not the case? Ie. the first one would be Philipp, then me (but I recuse myself), then Peter, then you (apparently you will recuse yourself as well, so) then Clemens. So we end up with Philipp instead of Nils?

Exciting, the first judgment!

**Comment by malte-l** [comment]
And perhaps Philipp should not close this pull request, so the discussion stays visible for the Judiciary to consider.

**Comment by cleborys** [comment]
The binary question, I assume, is "Have the kings of P and M moved?".
I am unsure about J needing to recuse himself, I'd think only P and M would be "interested" players and J is as "disinterested" as the rest of us - at least the judgement affects him in the same way as the rest of us.
J of course may nevertheless recuse himself / become ashamed.

**Comment by malte-l** [comment]
Why is that the binary question, if I saw correctly no one was contesting that P.'s king has *not* moved?
I suggest that after P. merges this pull request, the binary question to be posed is "Is the king of M. on the (0,0) square?"

**Comment by cleborys** [comment]
I guess it depends on how to read "A player who is involved in the disagreement must recuse himself".
I feel now that this applies to Phil, M and J.

**Comment by cleborys** [comment]
For some reason I thought philipps king moved. If that's not the case, he is of course not involved in the disagreement.

**Comment by malte-l** [comment]
I think "involved in the disagreement" is a bit vague. If J. invokes jugment, then I think one could say that they are involved in the disagreement. I don't see why I am necessarily more involved, as I only claim that the rules will do an action that moves a certain piece that is associated with me, but I am not actually taking any action. It is also totally unclear whether this action benefits me or not. I think that in the end, the people involved are Philipp, Josh, and myself. So I guess the judiciary is determined by that already, I forgot that Philipp is also involved as the person making the move in my earlier comment.

**Comment by Snark1994** [comment]
Mmm I would rather he didn't merge it; I'm declaring judgement against his intention to merge it. And as you say, this should have happened before the scores update, so for the purpose of judgement I think it's still Philipp's turn (so you're Nils' turn hasn't actually started yet, and is delayed by the judgement). In any case, I think Philipp is certainly involved.

I think I would interpret "invoking judgement" as "being involved", though perhaps involved to a lesser extent than those on whom judgement is being invoked. In any case, I recuse myself.

**Comment by AnonymousVeNomicPlayer** [comment]
It did move. And I think that shall be part of the judgement (at least if I were Josh, I would invoke judgment on the movement of both kings)

**Comment by cleborys** [comment]
In the proposed pull request, the king of Phillip has moved.

**Comment by Snark1994** [comment]
(and as far as I can see, Philipp's king is moved by the pull request)

**Comment by cleborys** [comment]
Man, I'm slow.

**Comment by malte-l** [comment]
@ P's king: Oh, sorry. I actually did not look at the commit, just at your comment. So you sent an email to yourself and only thought later that your king can thus move? Or wait, you got my email, and then looked into it, and then sent an email for yourself? Ok, that makes sense. Sorry for the confusion, I should have looked in the commits.

**Comment by cleborys** [comment]
So judgement vote on Sunday, Nils rule proposal on Monday.

**Comment by malte-l** [comment]
My fault for the confusion. So then perhaps "Are the kings of M. and P. on the (0,0) square?"

**Comment by AnonymousVeNomicPlayer** [comment]
Just for the records and official procedure to invoke judgment: I should make up my mind first on whether I want to merge this pull request or am convinced by Josh's argument. Depending on that it is either Josh or Malte who has to invoke judgment. In case I would decide not to merge this pull request, M. would have to invoke judgment because his king did not move and I cannot see a reason why J. shouldn't be a judge as he is not involved any more.

**Comment by AnonymousVeNomicPlayer** [comment]
@seeing the email: I thought about that when proposing the rule, there is no way to forbid looking into email. I thought about not allowing the proposer to move his king, but this can easily be implemented when kings are allowed to interact

**Comment by AnonymousVeNomicPlayer** [comment]
Concerning N.'s turn and the judgment I find the current rule pretty weird. I can see nothing that says that N.'s turn shall not continue, so we vote on his rule change on Sunday. The Jury shall vote on Thursday (the first voting day after the *next* proposal day, C. shall then propose a rule on Friday.

**Comment by AnonymousVeNomicPlayer** [comment]
Since I think that the rules do not say (J. could still convince me of the opposite) that a whole paragraph shall lose meaning just because the condition in its first sentence is not fulfilled, I would decide not to change my opinion on this issue. So J. has to invoke judgment against my pull-request, so we are both directly involved in the dispute. Since the dispute is also about the movement of M.'s king, I think that he also shall not be part of the Jury, so it would indeed be Niels, Clemens and Peter.

**Comment by malte-l** [comment]
So is it still P.'s turn now or N.'s turn? I tend to think it is N.'s turn, even though this pull request is something P. should do as part of their turn, as that is supposed to happen before updating the score, which ended P.'s turn. But that means that P. broke the rule of doing this first, but I guess there is no penalty for that and the remedy is to do it later (so now, in N.'s turn). So the procedure with the day on which the judges vote and the N.'s potential proposal etc. are as stated by P. in the second to last comment. I also agree with P.'s conclusion on who would be the judiciary.
Any other opinions on this?

**Comment by AnonymousVeNomicPlayer** [comment]
I must agree, I did not follow my own rule, because I updated points before updating the board. However, the main intention of updating the board first, was that this might later change the scores, which is not the case now. So I certainly broke a rule (shame on me), but it does not have any consequences at the moment.

**Comment by malte-l** [comment]
Yes, I agree, breaking that rule had/has no negative consequences, so no problem. But this interpretation does has as a consequence that it is then N.'s turn since earlier today when the score was updated.

**Comment by Snark1994** [comment]
I am unsure whose turn it is; either it's Nils' turn and he skipped it, or it's still Philipp's turn because this merge is part of Philipp's turn. I think it's fairest to say it's still Philipp's turn, and then let Nils take his turn on Monday (unless he tells us that he in fact was planning to skip his turn, in which case it can be Clemens' turn). 

Regarding my interpretation: I do not think the whole paragraph need be discounted, only that the way the rule works is at time A I send an email in order to cause an effect at time B; if there is no rule establishing this causal connection at the time I send the email, I do not think the effect should take place. (Or at least, I do not think the rules clearly state that this effect should take place.)

**Comment by Snark1994** [comment]
(and this whole mess with adjudications and turns should be cleared up. With the way things are set up, the proposer always ends up commenting and commiting and merging on the day after voting day. We should perhaps make it clear whose turn it is during that time period, and clarify what happens if judgement occurs during that turn, or move to a less time-rigid turn order.)

**Comment by malte-l** [comment]
Hm ok, so now we disagree even on whose turn it is... ;) ? We might need another jugment for that! But I also disagree with the interpretation that if it is N.'s turn, then the turn has been skipped, I think that is not the case, it is similar to my turn, when I also broke the rule of making a proposal on proposing day, but did not skip my turn.

I wholeheartedly agree with the statement that the judgement process and when turns start and end etc. should be cleared up in the next turns.

**Comment by Snark1994** [comment]
I would rather not have 2 judgements simultaneously in the current state of affairs, so am happy for it to be Nils' turn.
I think you *did* skip your turn, but I allowed you to break the rules in the spirit of a relaxed game. Similarly, if Nils posted a rule change now, then I would probably be fine with it as long as there was enough time to discuss it.

**Comment by cleborys** [comment]
In case anyone thinks there should be a judgement today, I judge that no-one has moved yet.
If the judgement is on Thursday, you will have some time to change my might, but maybe I can even introduce a rule that interacts with the outcome of the judgement and we will see what happens.

**Comment by cleborys** [comment]
*change my mind
My might is and remains untouchable

**Comment by AnonymousVeNomicPlayer** [comment]
You won't get a turn until then. So it should be hard to introduce a rule

**Comment by AnonymousVeNomicPlayer** [comment]
And I did not check the rules again, but I thought there is something in there like the voting shall be as for rules, so just announcing it publicly on github should not count.

**Comment by cleborys** [comment]
Y, hadn't read the stuff on Nils turn not having started, only him writing that he skipped :P

**Comment by AnonymousVeNomicPlayer** [comment]
Even if he skipped, you would have had to wait until the Judgment is resolved

**Comment by cleborys** [comment]
Yes, just wanted a fallback in case someone invokes judgement on me not judging or something

**Comment by cleborys** [comment]
Man, this is slow.

**Comment by AnonymousVeNomicPlayer** [comment]
You would just become ashamed which maybe you should be anyways for not reading the rules properly :P

**Comment by cleborys** [comment]
I judge that P has to pay a fine of 100pts for misdemeanor against the high court of justice, breaker of chains, beacon of light and glory.

**Comment by AnonymousVeNomicPlayer** [comment]
I did not intend to insult the high court of justice, breaker of chains, beacon of light and glory and would therefore like to beg the high court of justice, breaker of chains, beacon of light and glory to take my deepest apologies. I swear that I will never ever insult the high court of justice, breaker of chains, beacon of light and glory again.

**Comment by cleborys** [comment]
Your insurrection shall hereby be foregone. For now.

**Comment by cleborys** [comment]
So, whom does the high court of justice, breaker of chains, beacon of light and glory send his judgement mail to?
Phil, the petty insurgent?

**Comment by malte-l** [comment]
I think the best option is sending an identical email to N and P. There was a discussion on whose turn it is before, and I said it was N.'s turn. J. was of a different opinion but wrote that they would not invoke judgment on that in order not to have nested judgments. I also wasn't sure and wouldn't have contested the other interpretation, but I think "it is N's turn" was stated clearest/first, so I suggest going with that unless anyone invokes judgment on it. To be safe you might send an email to both P. and N., so that your vote is counted independently of how that hypothetical nested jugment goes (but then if it comes to that we would have that problem again unless all judges do that...) Ok I think the issue of whose turn it is can be avoided for the purpose of voting for this judgment by sending the same email to both.
I also just want to add that that rule 211 doesn't say what "voting" means for judgments, and rule 120 only discusses "voting on rules", but I think applying that in analogy is probably the best option.

**Comment by AnonymousVeNomicPlayer** [comment]
But to be serious: I don't know, as M. said it is safest to send it both to me and N.

**Comment by AnonymousVeNomicPlayer** [comment]
And by the way, who are the judges now? I still think, that if P. left the game yesterday his vote cannot count. And even though this sounds strange, M. is the next least involved person and should in my opinion replace him.

**Comment by malte-l** [comment]
Right, if the vote is today and Peter stopped being a player yesterday, then they can't be a juge today either.
Originally I think J., P. and myself recused ourselves. Now the bullet point about that became ignored because it is no longer possible for all involved to be recused. The question is, do P. and J. have to recuse themselves again or do the recusements still stand but it is now possible to un-recuse oneself (perhaps if one is least-involved among the recused)? As I think we want to finish the judgment today I will assume that P. and J.  are still recused and as the probably formally least-involved player among the previously recused people I un-recuse myself and just sent an email with a vote.
If J. has an argument for why they should be judge instead now and also vote before midnight, then I won't invoke judgment on that, I just hope we can finish the judgme t successfully today.
As Peter is still in the player list, I also won't contest if they vote. If they really left, then N. or tomorrow (in case the judgment ends today) C. should remove them from the player list.

**Comment by AnonymousVeNomicPlayer** [comment]
I received only two mails (of M. and C.), so I was hoping that N. had sent an email to himself and that he would announce the result. If N. did not do this, then he should become Ashamed and the Judgment is repeated on Sunday (?)

**Comment by AnonymousVeNomicPlayer** [comment]
Btw, the emails I received ruled differently, so N.'s vote really counts.

**Comment by AnonymousVeNomicPlayer** [comment]
As you might know I will be on holiday for the next two weeks. In particular this means that I probably don't want to spend much time on lengthy Nomic discussions, so I will be much less active in the next two weeks. I hope that I will at least look a few times what is happening, but I can't promise anything.  (Maybe the Judgment takes some more time, then I won't miss that much ;))

**Comment by malte-l** [comment]
Can someone contact N. through some reliable channel in order to remind them to announce the results of the vote on judgment? And that if they didn't receive a vote from themselves (assuming C. in fact sent their vote to N.), that the vote will be repeated tomorrow, and that they should vote then.

**Comment by malte-l** [comment]
Is Nils still playing? They haven't reacted for more than a week. Perhaps someone that knows them outside of the game can contact them to find out?

**Comment by nilsbeyer** [comment]
No I am not currently putting much time into the game.

**Comment by malte-l** [comment]
So do you want to quit the game? The "no" seems to indicate so, but "not putting much time into the game" seems to indicate you still play, just with less time.
If you still want to continue playing I would encourage you to reveal the results of the judgment vote (as well as voting yourself), as the game can't proceed without it and has because of that has been delayed for over a week. If not, it would be good if you could say explicitly that you don't want to play anymore.

**Comment by nilsbeyer** [comment]
Yes. I meant to say that I really like the game but currently don't have enough time for it, which is not fair to you.
But I guess it would really help you if I officially stated:
I quit the game!

**Comment by cleborys** [comment]
The Honorable, the Chief Justice and the Associate Justices of the Supreme Court of the United States. Oyez! Oyez! Oyez! All persons having business before the Honorable, the Supreme Court of the Untied States, are admonished to draw near and give their attention, for the Court is now sitting. God save the Untied States and this Honorable Court!

**Comment by cleborys** [comment]
The honourable court hath spoken that all players are currently positioned on (0,0).

**Pull request closed without merging**
