### PR TITLE
Rule 302: make 119 mutable

### PR DESCRIPTION
**Pull request by Snark1994**
My proposal is to make rule 119 (handling voting procedures) mutable.

I am unhappy with the public voting on the GitHub, and would like to change to a better system. If it makes a difference to anyone, my preferred solution is "everyone emails their vote to the proposer, who publicly announces them once he/she has received them all on voting day; the proposer must announce the votes honestly, and the players must not claim to have submitted something different from what they actually sent." (The public announcement allows players to check that they are not being cheated by the proposer.) Of course, this is really up to whoever proposes an amendment to rule formerly-known-as-119.

I have also made a lot of formatting changes to the markdown in order to make the list numbering display correctly. Only the last commit in the pull request contains the actual rule change. This closes issue #2  .

### CODE REVIEW

**Comment by Smaug123** [comment]
I'm not sure about this method of laying out immutable vs mutable. If we create a mutable rule and then an immutable rule, the numberings get a bit weird: we have numbers in the 300s in the Immutable section, and numbers in the 300s in the Mutable section. Not saying there's an obvious better way to do it, but the alternative is to have simply a list of rules and then each is tagged with "mutable" or "immutable", à la [EnAct](https://enact.jwjr.co.uk/active_rules), my other active game.

**Comment by Snark1994** [comment]
I think rules 102 and 108 are clear on how to number rules currently, but your suggestion is sensible and I would be up for adopting it if proposed.

**Comment by nilsbeyer** [comment]
VOTE: yes

**Comment by malte-l** [comment]
VOTE: yes

**Comment by AnonymousVeNomicPlayer** [comment]
I think that in principle people should not vote before the official voting day, which is tomorrow for the current rule suggestion. In principle Josh could still change his rule and it is not completely clear to me whether votes on the previous day should be considered valid according to the rules.

**Comment by AnonymousVeNomicPlayer** [comment]
Also let me just say that I do agree that changing the voting system is a good idea and therefore I'm planning to approve this rule change.

**Comment by malte-l** [comment]
Oops, the days were changed so often I couldn't remember and just assumed it was today as there was already a vote...  Will make sure to check next time! (I agree with AnonymousVeNomicPlayer's points about not voting early)

**Comment by Snark1994** [comment]
I'd like to point out that the day changes every day, so that's not a great excuse.

**Comment by malte-l** [comment]
I don't understand the previous comment. Rules 215 and 216 certanly fix on what day of the week things happen and that doesn't change. I was refering to the fact that in the discussions the days mentioned in that rule were moved back and forth, ending up with 1 discussion day for friday proposals, but 2 for monday proposals, which is where the mistake comes from.

Regarding the validity of votes, I think the rules only state that voting has to be completed by the end of the voting day for that turn (rule 218). Though it might be unclear what happens if the proposal indeed changes.

**Comment by malte-l** [comment]
The order in  which players move is defined by their names as in the players file, but here when voting people use github accounts with names that not necessarily match up. Can this information be shared somehow? I am Malte L. by the way. (I don't necessarily care about the names, but it might be relevant to know when it will be peoples turn when interpreting their comments and voting behaviour).

**Comment by malte-l** [comment]
VOTE: yes

**Comment by cleborys** [comment]
I think the "changes every day" comment was just snark being snark.
I can match every account that has come up so far to a real person and am happy to do so (I'll send you a mail, so it's not publically on the internet)

**Comment by nilsbeyer** [comment]
It was pretty funny actually. xD
And i would certainly not oppose a rule change that made votes before voiting day invalid.

**Comment by malte-l** [comment]
Ah, I see. In any case, I hope everyone is convinced that I did *not* vote early as part of some devious tactic...

**Comment by Snark1994** [comment]
@malte-l : yes, I was merely making a joke that the day of the week changes every day.

**Comment by Snark1994** [comment]
VOTE: approve

**Comment by AnonymousVeNomicPlayer** [comment]
VOTE: approve

**Comment by cleborys** [comment]
VOTE: approve

**Comment by nilsbeyer** [comment]
VOTE: approve

**Comment by nilsbeyer** [comment]
VOTE: no

**Comment by nilsbeyer** [comment]
VOTE: yes

**Comment by nilsbeyer** [comment]
did I break rule 207?
what happens if some one breaks a rule?

**Comment by Snark1994** [comment]
I would argue you haven't broken rule 207, you've merely changed what your one vote says.
As to what happens if you do break the rules, we would kindly ask you not to (indeed, by playing a game we have implicitly agreed to some sort of meta-rule that says we will follow the rules; exactly what the meta-rule is has been the subject of some debate, but my favoured version is "I will follow the rules in the form that they are currently enacted"). If rule-breaking were to happen accidentally (e.g. a player forgetting to vote) I guess it would be up to a judge to rule on the outcome; at some point in the future, I would hope we would pass a rule that makes it more explicit.

**Comment by cleborys** [comment]
Mostly, opinions differ on what happens, if rule 101 is ever repealed. For the moment it is advised not to.

**Comment by Smaug123** [comment]
VOTE: yes

**Comment by peteroestergaard** [comment]
Vote: yes

**Comment by Snark1994** [comment]
I intend to count this as an accepted proposal, despite the fact that two votes were not made in time. The rules are unclear on this point (players "must" vote on voting days, but we don't specify what happens if they don't; proposals are approved if the vote is unanimously in favour, which in this case it is).

If anyone disagrees with this and would like me not to count this as accepted, _i.e._ intends to invoke Judgement, then please let me know by this evening. If not I'll merge it into master.

**Comment by malte-l** [comment]
I interpret 211 in the way that thinking that something does not conform to the rules does not mean that that person is required to invoke judgement. Because I also want this rule passed, I thus see no reason to invoke judgement, but this shall not be taken as agreement with this interpretation of when rules are passed in the future.

**Pull request merged**
